source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '13.6'
use_frameworks!

target 'PlayerUICustomization' do
	pod 'Brightcove-Player-Core/XCFramework'
end
