source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BCOVSpecs.git'

platform :ios, '7.0'

pod 'Brightcove-Player-SDK', '4.3'
pod 'Brightcove-Player-SDK-Widevine', '1.2'

