require_relative '../../Podfile.common'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '17.0'

use_frameworks!

target 'SwiftUIPlayerIMA' do
  brightcove_pod 'Brightcove-Player-IMA'
end
