source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

use_frameworks!

platform :tvos, '13.4'

target 'BasicPulsetvOSPlayer' do
  pod 'Brightcove-Player-Pulse/XCFramework'
end
