source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BCOVSpecs.git'

use_frameworks!

platform :ios, '7.0'

target 'BasicFreewheelPlayer' do
	pod 'Brightcove-Player-SDK'
	pod 'Brightcove-Player-SDK-FW'
end
