source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

use_frameworks!

platform :ios, '13.6'

target 'BasicFreewheelPlayer' do
  pod 'Brightcove-Player-FreeWheel/XCFramework'
end
