require_relative '../../Podfile.common'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '12.0'

use_frameworks!

target 'VideoCloudBasicPlayer' do
  brightcove_pod 'Brightcove-Player-Core'
end
