source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

use_frameworks!

platform :ios, '11.0'

target 'SLS_IMA-Player' do
	pod 'Brightcove-Player-SSAI'
	pod 'Brightcove-Player-IMA'
end
