require_relative '../../Podfile.common'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :tvos, '14.0'

use_frameworks!

target 'SLS_IMA-Player' do
  brightcove_pod 'Brightcove-Player-SSAI'
  brightcove_pod 'Brightcove-Player-IMA'
end
