source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '10.0'

use_frameworks!

target 'FairPlayIMAPlayer' do
	pod 'Brightcove-Player-IMA'
end
