source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'BasicSidecarSubtitlesPlayer' do
	pod 'Brightcove-Player-SDK-SidecarSubtitles', '~> 2.0.0'
	pod 'Brightcove-Player-SDK', '~> 5.0.0'
end
