source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '13.6'

use_frameworks!

target 'Video360Player' do
	pod 'Brightcove-Player-Core/XCFramework'
end
