source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

use_frameworks!

platform :tvos, '11.0'

target 'NativeControlsIMAPlayer_tvOS' do
	pod 'Brightcove-Player-IMA'
end
