source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

use_frameworks!

platform :tvos, '13.4'

target 'NativeControlsIMAPlayer_tvOS' do
	pod 'Brightcove-Player-IMA/XCFramework'
end
