require_relative '../../Podfile.common'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '14.0'

use_frameworks!

target 'BasicCastPlayer' do
  brightcove_pod 'Brightcove-Player-GoogleCast'
end
