source 'https://github.com/brightcove/BrightcoveSpecs.git'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '11.0'

use_frameworks!

target 'BrightcoveCastReceiver' do
  pod 'Brightcove-Player-GoogleCast/Bluetooth/XCFramework'
end
