source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '14.0'

use_frameworks!

target 'BrightcoveCastReceiver' do
  pod 'Brightcove-Player-GoogleCast/Bluetooth/XCFramework'
end
