source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

use_frameworks!

platform :ios, '13.6'

target 'BasicSSAIPlayer' do
	pod 'Brightcove-Player-SSAI/XCFramework'
end
