source 'https://github.com/brightcove/BrightcoveSpecs.git'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '10.0'

use_frameworks!

target 'BasicCastPlayer' do
  pod 'Brightcove-Player-GoogleCast'
end
