source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BCOVSpecs.git'

use_frameworks!

platform :ios, '8.0'

target 'BasicOmniturePlayer' do
	pod 'Brightcove-Player-SDK'
	pod 'Brightcove-Player-SDK-Omniture'
end
