source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '13.6'
use_frameworks!

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'PlayerReactNative' do
  
  config = use_native_modules!
  use_react_native!(path: config['reactNativePath'])
  
  pod 'Brightcove-Player-Core/XCFramework'

end
