source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

use_frameworks!

platform :tvos, '13.4'

target 'AppleTV' do
  pod 'Brightcove-Player-Core/XCFramework'
end
