source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :tvos, '12.0'

use_frameworks!

target 'AppleTV' do
  pod 'Brightcove-Player-Core/XCFramework'
end
