source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '14.0'

use_frameworks!

target 'BasicDAIPlayer' do

  # Pods for BasicDAIPlayer
  pod 'Brightcove-Player-DAI/XCFramework'

end
