source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'FairPlayIMAPlayer' do
  pod 'Brightcove-Player-SDK-IMA'
  pod 'Brightcove-Player-SDK-FairPlay/dynamic'
  pod 'Brightcove-Player-SDK'
end
