source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'BasicFairPlayPlayer' do
	pod 'Brightcove-Player-SDK-FairPlay/dynamic', '~> 1.0.0'
	pod 'Brightcove-Player-SDK', '~> 5.0.0'
end
