source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'BasicFairPlayPlayer' do
  pod 'Brightcove-Player-SDK-FairPlay/dynamic'
  pod 'Brightcove-Player-SDK/dynamic'
end
