source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

use_frameworks!

platform :ios, '8.0'

target 'BasicFairPlayPlayer' do
  pod 'Brightcove-Player-Core/dynamic'
end
