source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

use_frameworks!

platform :ios, '13.6'

flutter_application_path = '../flutter_app'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'PlayerFlutter' do

  pod 'Brightcove-Player-Core/XCFramework'
  install_all_flutter_pods(flutter_application_path)

end
