source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '15.0'

use_frameworks!

target 'SharePlayPlayer' do
  pod 'Brightcove-Player-Core/XCFramework'
end
