source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :tvos, '14.0'

use_frameworks!

target 'BasicDAIPlayer' do
  pod 'Brightcove-Player-DAI/XCFramework'
end